<a href="https://colab.research.google.com/github/Shakilgithub20/Basic-ML/blob/main/Implement_the_apriori_algorithm_using_the_groceries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install apyori

Requirement already satisfied: apyori in /usr/local/lib/python3.7/dist-packages (1.1.2)

##Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from apyori import apriori

##Data Preprocessing

In [ ]:
dataset = pd.read_csv('/content/groceries.csv', header = None)
dataset.head(10)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,whole milk,butter,yogurt,rice,abrasive cleaner,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,rolls/buns,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,other vegetables,UHT-milk,rolls/buns,bottled beer,liquor (appetizer),NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,pot plants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,whole milk,cereals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9835 entries, 0 to 9834
Data columns (total 32 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       9835 non-null   object
 1   1       7676 non-null   object
 2   2       6033 non-null   object
 3   3       4734 non-null   object
 4   4       3729 non-null   object
 5   5       2874 non-null   object
 6   6       2229 non-null   object
 7   7       1684 non-null   object
 8   8       1246 non-null   object
 9   9       896 non-null    object
 10  10      650 non-null    object
 11  11      468 non-null    object
 12  12      351 non-null    object
 13  13      273 non-null    object
 14  14      196 non-null    object
 15  15      141 non-null    object
 16  16      95 non-null     object
 17  17      66 non-null     object
 18  18      52 non-null     object
 19  19      38 non-null     object
 20  20      29 non-null     object
 21  21      18 non-null     object
 22  22      14 non-null     object
 23  23      8 non-null      object
 24  24      7 non-null      object
 25  25      7 non-null      object
 26  26      6 non-null      object
 27  27      5 non-null      object
 28  28      4 non-null      object
 29  29      1 non-null      object
 30  30      1 non-null      object
 31  31      1 non-null      object
dtypes: object(32)
memory usage: 2.4+ MB

In [ ]:
transactions = []
for i in range(0, 9835):
  transactions.append([str(dataset.values[i,j]) for j in range(0, 32)])

##Training the Apriori model on the dataset

In [ ]:
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

In [ ]:
results = list(rules)
results

[RelationRecord(items=frozenset({'hamburger meat', 'Instant food products'}), support=0.003050330452465684, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Instant food products'}), items_add=frozenset({'hamburger meat'}), confidence=0.379746835443038, lift=11.42143769597027)]),
 RelationRecord(items=frozenset({'whipped/sour cream', 'baking powder'}), support=0.004575495678698526, ordered_statistics=[OrderedStatistic(items_base=frozenset({'baking powder'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.25862068965517243, lift=3.607850330154072)]),
 RelationRecord(items=frozenset({'root vegetables', 'beef'}), support=0.017386883579054397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'beef'}), items_add=frozenset({'root vegetables'}), confidence=0.3313953488372093, lift=3.0403668431100312)]),
 RelationRecord(items=frozenset({'whipped/sour cream', 'berries'}), support=0.009049313675648195, ordered_statistics=[OrderedStatistic(items_base=frozenset({'berries'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.27217125382262997, lift=3.796885505454703)]),
 RelationRecord(items=frozenset({'liquor', 'bottled beer'}), support=0.004677173360447382, ordered_statistics=[OrderedStatistic(items_base=frozenset({'liquor'}), items_add=frozenset({'bottled beer'}), confidence=0.4220183486238532, lift=5.240594013529793)]),
 RelationRecord(items=frozenset({'bottled beer', 'red/blush wine'}), support=0.004880528723945094, ordered_statistics=[OrderedStatistic(items_base=frozenset({'red/blush wine'}), items_add=frozenset({'bottled beer'}), confidence=0.253968253968254, lift=3.1537598204264876)]),
 RelationRecord(items=frozenset({'flour', 'margarine'}), support=0.0037620742247076767, ordered_statistics=[OrderedStatistic(items_base=frozenset({'flour'}), items_add=frozenset({'margarine'}), confidence=0.21637426900584797, lift=3.6945155133203382)]),
 RelationRecord(items=frozenset({'flour', 'sugar'}), support=0.00498220640569395, ordered_statistics=[OrderedStatistic(items_base=frozenset({'flour'}), items_add=frozenset({'sugar'}), confidence=0.28654970760233917, lift=8.46311223504206)]),
 RelationRecord(items=frozenset({'whipped/sour cream', 'flour'}), support=0.004067107269954245, ordered_statistics=[OrderedStatistic(items_base=frozenset({'flour'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.23391812865497078, lift=3.263240844427855)]),
 RelationRecord(items=frozenset({'root vegetables', 'herbs'}), support=0.007015760040671073, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herbs'}), items_add=frozenset({'root vegetables'}), confidence=0.43124999999999997, lift=3.956477378731343)]),
 RelationRecord(items=frozenset({'processed cheese', 'white bread'}), support=0.004168784951703101, ordered_statistics=[OrderedStatistic(items_base=frozenset({'processed cheese'}), items_add=frozenset({'white bread'}), confidence=0.25153374233128833, lift=5.975445303932901)]),
 RelationRecord(items=frozenset({'rice', 'root vegetables'}), support=0.00315200813421454, ordered_statistics=[OrderedStatistic(items_base=frozenset({'rice'}), items_add=frozenset({'root vegetables'}), confidence=0.4133333333333334, lift=3.792101990049752)]),
 RelationRecord(items=frozenset({'sliced cheese', 'sausage'}), support=0.007015760040671073, ordered_statistics=[OrderedStatistic(items_base=frozenset({'sliced cheese'}), items_add=frozenset({'sausage'}), confidence=0.2863070539419087, lift=3.047434930215013)])]

##Putting the results well organised into a Pandas DataFrame

In [ ]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

##Displaying the results non sorted

In [ ]:
resultsinDataFrame

           Left Hand Side     Right Hand Side   Support  Confidence       Lift
0   Instant food products      hamburger meat  0.003050    0.379747  11.421438
1           baking powder  whipped/sour cream  0.004575    0.258621   3.607850
2                    beef     root vegetables  0.017387    0.331395   3.040367
3                 berries  whipped/sour cream  0.009049    0.272171   3.796886
4                  liquor        bottled beer  0.004677    0.422018   5.240594
5          red/blush wine        bottled beer  0.004881    0.253968   3.153760
6                   flour           margarine  0.003762    0.216374   3.694516
7                   flour               sugar  0.004982    0.286550   8.463112
8                   flour  whipped/sour cream  0.004067    0.233918   3.263241
9                   herbs     root vegetables  0.007016    0.431250   3.956477
10       processed cheese         white bread  0.004169    0.251534   5.975445
11                   rice     root vegetables  0.003152    0.413333   3.792102
12          sliced cheese             sausage  0.007016    0.286307   3.047435

##Displaying the results sorted by descending lifts

In [ ]:
resultsinDataFrame.nlargest(n = 10, columns = 'Lift')

           Left Hand Side     Right Hand Side   Support  Confidence       Lift
0   Instant food products      hamburger meat  0.003050    0.379747  11.421438
7                   flour               sugar  0.004982    0.286550   8.463112
10       processed cheese         white bread  0.004169    0.251534   5.975445
4                  liquor        bottled beer  0.004677    0.422018   5.240594
9                   herbs     root vegetables  0.007016    0.431250   3.956477
3                 berries  whipped/sour cream  0.009049    0.272171   3.796886
11                   rice     root vegetables  0.003152    0.413333   3.792102
6                   flour           margarine  0.003762    0.216374   3.694516
1           baking powder  whipped/sour cream  0.004575    0.258621   3.607850
8                   flour  whipped/sour cream  0.004067    0.233918   3.263241